spring:
  datasource:
    url: jdbc:mysql://localhost:3306/website
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-init-sql: SET NAMES utf8mb4 COLLATE utf8mb4_general_ci
      connection-timeout: 10000
      validation-timeout: 10000
      maximum-pool-size: 10
      minimum-idle: 10
      max-lifetime: 600000
  mvc:
    static-path-pattern: static/**
  thymeleaf:
    suffix: .html
    prefix: classPath:templates/

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    generate-ddl: true
decorator:
  datasource:
    p6spy:
      enable-logging: true
server:
  port: 5000